name: CI Pipeline for ByteShield Chatbot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust to your project's target framework (e.g., 6.0.x or 8.0.x)

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ByteShield-Chatbot.csproj

      # Build the project
      - name: Build
        run: dotnet build ByteShield-Chatbot.csproj --no-restore --configuration Release

      # Validate required files
      - name: Validate project files
        run: |
          if [ ! -f "ByteShield-Chatbot.csproj" ]; then echo "CSProj file missing!" && exit 1; fi
          if [ ! -f "Program.cs" ]; then echo "Program.cs missing!" && exit 1; fi
          if [ ! -f "sound.wav" ]; then echo "sound.wav missing!" && exit 1; fi
          if [ ! -f "logo.png" ]; then echo "logo.png missing!" && exit 1; fi
          if [ ! -f "memory.txt" ]; then echo "memory.txt missing!" && exit 1; fi

      # Optional: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ${{ github.workspace }}/bin/Release/
